#!/usr/bin/env python3
"""Assemble the showcase site: reads every spec + the 4 translators' output
(already generated by run_altair.py / run_vlapi.mjs / run_d3.mjs /
render_ggplot.R / render_thumbnails.mjs) and writes showcase/index.html plus
one showcase/examples/<name>/index.html per spec.

The landing page mirrors https://vega.github.io/vega-lite/examples/'s own
category structure (see gallery_structure.py) for every example name that
gallery lists, with everything else grouped into an "Additional Examples"
catch-all by filename-prefix category."""
import hashlib
import json
import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from gallery_structure import load_gallery_sections

REPO = Path(__file__).resolve().parent.parent
SPECS_DIR = REPO / "vega-lite-example-specs"
SHOWCASE = REPO / "showcase"
EXAMPLES_DIR = SHOWCASE / "examples"
RENDERS_DIR = SHOWCASE / "renders"
RENDERS_MATPLOTLIB_DIR = SHOWCASE / "renders_matplotlib"
THUMBS_DIR = SHOWCASE / "thumbs_png"

env = Environment(
    loader=FileSystemLoader(str(Path(__file__).parent / "templates")),
    autoescape=select_autoescape(["html", "j2"]),
)


def humanize(name: str) -> str:
    return " ".join(w.capitalize() for w in name.split("_"))


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def load_status(fname):
    p = SHOWCASE / fname
    return json.loads(p.read_text()) if p.exists() else {}


def read_code(example_dir: Path, fname: str) -> str:
    p = example_dir / fname
    return p.read_text() if p.exists() else ""


def main():
    status_altair = load_status("status_altair.json")
    status_vlapi = load_status("status_vlapi.json")
    status_d3 = load_status("status_d3.json")
    status_plot = load_status("status_plot.json")
    status_ggplot = load_status("status_ggplot.json")
    status_matplotlib = load_status("status_matplotlib.json")

    gallery_sections, gallery_titles = load_gallery_sections()
    gallery_names = set(gallery_titles.keys())

    spec_files = sorted(SPECS_DIR.glob("*.vl.json"))
    names = [f.name[: -len(".vl.json")] for f in spec_files]

    examples = []
    for i, spec_path in enumerate(spec_files):
        name = names[i]
        raw = json.loads(spec_path.read_text())
        description = raw.get("description") or raw.get("title") or ""
        if isinstance(description, dict):
            description = description.get("text", "")
        category = name.split("_")[0]
        title = gallery_titles.get(name) or humanize(name)

        # Relative data/image references (e.g. "data/cars.json", or an
        # "image" mark's per-row url field value) are left exactly as
        # written in the original spec -- the page resolves them at render
        # time via vega-embed's loader baseURL (see example.html.j2) rather
        # than needing this spec rewritten ahead of time. Also means the
        # "View raw spec JSON" panel shows the actual, unmodified spec.
        display_spec = json.loads(spec_path.read_text())
        display_spec.pop("$schema", None)

        example_dir = EXAMPLES_DIR / name

        altair_status = status_altair.get(name, {"ok": False, "error": "not run"})
        vlapi_status = status_vlapi.get(name, {"ok": False, "error": "not run"})
        d3_status = status_d3.get(name, {"ok": False, "error": "not run"})
        plot_status = status_plot.get(name, {"ok": False, "error": "not run"})
        ggplot_status = status_ggplot.get(name, {"ok": False, "error": "not run"})
        matplotlib_status = status_matplotlib.get(name, {"ok": False, "error": "not run"})
        has_png = (RENDERS_DIR / f"{name}.png").exists()
        has_matplotlib_png = (RENDERS_MATPLOTLIB_DIR / f"{name}.png").exists()
        has_thumb = (THUMBS_DIR / f"{name}.png").exists()

        ctx = dict(
            name=name,
            title=title,
            description=description,
            category=category,
            in_gallery=name in gallery_names,
            has_thumb=has_thumb,
            spec_json=json.dumps(display_spec),
            altair={"ok": altair_status.get("ok", False), "error": altair_status.get("error", ""),
                    "code": read_code(example_dir, "altair.py")},
            vlapi={"ok": vlapi_status.get("ok", False), "error": vlapi_status.get("error", ""),
                   "code": read_code(example_dir, "vlapi.js")},
            d3={"ok": d3_status.get("ok", False), "translated": d3_status.get("translated", d3_status.get("ok", False)),
                "error": d3_status.get("error", ""), "code": read_code(example_dir, "d3.js"),
                # A same-URL `import` of d3.js is exactly the kind of request
                # browsers cache hardest (ES modules, no query string) -- a
                # rebuild that changes d3.js's content but not its path can
                # otherwise leave a browser silently running the *previous*
                # build's module on a plain refresh. Busting on a hash of the
                # actual content (not e.g. current time) means the URL only
                # changes when the code actually did.
                "cachebust": hashlib.md5(read_code(example_dir, "d3.js").encode()).hexdigest()[:10]},
            plot={"ok": plot_status.get("ok", False), "translated": plot_status.get("translated", plot_status.get("ok", False)),
                  "error": plot_status.get("error", ""), "code": read_code(example_dir, "plot.js"),
                  # Same same-URL-caching concern as d3.js above.
                  "cachebust": hashlib.md5(read_code(example_dir, "plot.js").encode()).hexdigest()[:10]},
            ggplot={"ok": ggplot_status.get("ok", False), "error": ggplot_status.get("error", ""),
                    "code": read_code(example_dir, "ggplot.R"), "has_png": has_png},
            matplotlib={"ok": matplotlib_status.get("ok", False), "error": matplotlib_status.get("error", ""),
                        "code": read_code(example_dir, "matplotlib.py"), "has_png": has_matplotlib_png},
            prev_name=names[i - 1] if i > 0 else None,
            next_name=names[i + 1] if i < len(names) - 1 else None,
        )
        examples.append(ctx)

    example_tpl = env.get_template("example.html.j2")
    for ctx in examples:
        out = example_tpl.render(**ctx)
        (EXAMPLES_DIR / ctx["name"]).mkdir(parents=True, exist_ok=True)
        (EXAMPLES_DIR / ctx["name"] / "index.html").write_text(out)

    by_name = {ex["name"]: ex for ex in examples}

    def card(ex):
        return dict(
            name=ex["name"], title=ex["title"], description=ex["description"],
            has_thumb=ex["has_thumb"],
            altair_ok=ex["altair"]["ok"], vlapi_ok=ex["vlapi"]["ok"], d3_ok=ex["d3"]["ok"], plot_ok=ex["plot"]["ok"],
            ggplot_ok=ex["ggplot"]["ok"] and ex["ggplot"]["has_png"],
            matplotlib_ok=ex["matplotlib"]["ok"] and ex["matplotlib"]["has_png"],
        )

    # Mirror the official gallery's section > subsection > item structure for
    # every name it lists (100% of them exist in this corpus too, since both
    # come from the same vega-lite repo's examples/specs/ directory).
    sections = []
    for gs in gallery_sections:
        subsections = []
        for sub in gs["subsections"]:
            items = [card(by_name[n]) for n in sub["items"] if n in by_name]
            if items:
                subsections.append({"h3": sub["h3"], "cards": items})
        if subsections:
            sections.append({"h2": gs["h2"], "slug": slugify(gs["h2"]), "subsections": subsections})

    # Everything not in the official gallery: grouped by filename-prefix
    # category (e.g. "bar_foo" -> "bar"), alphabetically.
    leftover = [ex for ex in examples if not ex["in_gallery"]]
    by_category = {}
    for ex in leftover:
        by_category.setdefault(ex["category"], []).append(ex)
    extra_subsections = [
        {"h3": cat, "cards": [card(ex) for ex in sorted(by_category[cat], key=lambda e: e["name"])]}
        for cat in sorted(by_category)
    ]
    if extra_subsections:
        sections.append({
            "h2": "Additional Examples (test corpus, not in the curated gallery)",
            "slug": "additional-examples",
            "subsections": extra_subsections,
        })

    index_tpl = env.get_template("index.html.j2")
    (SHOWCASE / "index.html").write_text(index_tpl.render(
        sections=sections,
        total_count=len(examples),
        gallery_count=len(gallery_names),
    ))

    print(f"Built {len(examples)} example pages + index.html")
    for sysname, key in [("altair", "altair"), ("vlapi", "vlapi"), ("d3", "d3"), ("plot", "plot"), ("ggplot2", "ggplot"), ("matplotlib", "matplotlib")]:
        ok = sum(1 for ex in examples if (ex[key]["ok"] and (key not in ("ggplot", "matplotlib") or ex[key]["has_png"])))
        print(f"  {sysname}: {ok}/{len(examples)} ok")


if __name__ == "__main__":
    main()
