#!/usr/bin/env python3
"""Assemble the showcase site: reads every spec + the 4 translators' output
(already generated by run_altair.py / run_vlapi.mjs / run_d3.mjs /
render_ggplot.R / render_thumbnails.mjs) and writes showcase/index.html plus
one showcase/examples/<name>/index.html per spec.

The landing page mirrors https://vega.github.io/vega-lite/examples/'s own
category structure (see gallery_structure.py) for every example name that
gallery lists, with everything else grouped into an "Additional Examples"
catch-all by filename-prefix category."""
import json
import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from gallery_structure import load_gallery_sections

REPO = Path(__file__).resolve().parent.parent
SPECS_DIR = REPO / "vega-lite-example-specs"
SHOWCASE = REPO / "showcase"
EXAMPLES_DIR = SHOWCASE / "examples"
RENDERS_DIR = SHOWCASE / "renders"
THUMBS_DIR = SHOWCASE / "thumbs_png"

env = Environment(
    loader=FileSystemLoader(str(Path(__file__).parent / "templates")),
    autoescape=select_autoescape(["html", "j2"]),
)


def humanize(name: str) -> str:
    return " ".join(w.capitalize() for w in name.split("_"))


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def rewrite_urls(obj):
    """Point every relative data.url reference at the local showcase/data/
    copy, relative to *this page's own location* (examples/<name>/index.html,
    two directories below showcase/) rather than domain-root-absolute --
    the previous "/data/..." form only worked when the site happened to be
    served from a server's actual root, breaking as soon as it's deployed
    under a subpath (e.g. https://host/vl2x/showcase/...). A genuine
    external URL (http/https) is left untouched and used directly."""
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k == "url" and isinstance(v, str) and not v.startswith(("http://", "https://")):
                obj[k] = "../../" + v.lstrip("/")
            else:
                rewrite_urls(v)
    elif isinstance(obj, list):
        for v in obj:
            rewrite_urls(v)


def load_status(fname):
    p = SHOWCASE / fname
    return json.loads(p.read_text()) if p.exists() else {}


def read_code(example_dir: Path, fname: str) -> str:
    p = example_dir / fname
    return p.read_text() if p.exists() else ""


def main():
    status_altair = load_status("status_altair.json")
    status_vlapi = load_status("status_vlapi.json")
    status_d3 = load_status("status_d3.json")
    status_ggplot = load_status("status_ggplot.json")

    gallery_sections, gallery_titles = load_gallery_sections()
    gallery_names = set(gallery_titles.keys())

    spec_files = sorted(SPECS_DIR.glob("*.vl.json"))
    names = [f.name[: -len(".vl.json")] for f in spec_files]

    examples = []
    for i, spec_path in enumerate(spec_files):
        name = names[i]
        raw = json.loads(spec_path.read_text())
        description = raw.get("description") or raw.get("title") or ""
        if isinstance(description, dict):
            description = description.get("text", "")
        category = name.split("_")[0]
        title = gallery_titles.get(name) or humanize(name)

        display_spec = json.loads(spec_path.read_text())
        display_spec.pop("$schema", None)
        rewrite_urls(display_spec)

        example_dir = EXAMPLES_DIR / name

        altair_status = status_altair.get(name, {"ok": False, "error": "not run"})
        vlapi_status = status_vlapi.get(name, {"ok": False, "error": "not run"})
        d3_status = status_d3.get(name, {"ok": False, "error": "not run"})
        ggplot_status = status_ggplot.get(name, {"ok": False, "error": "not run"})
        has_png = (RENDERS_DIR / f"{name}.png").exists()
        has_thumb = (THUMBS_DIR / f"{name}.png").exists()

        ctx = dict(
            name=name,
            title=title,
            description=description,
            category=category,
            in_gallery=name in gallery_names,
            has_thumb=has_thumb,
            spec_json=json.dumps(display_spec),
            altair={"ok": altair_status.get("ok", False), "error": altair_status.get("error", ""),
                    "code": read_code(example_dir, "altair.py")},
            vlapi={"ok": vlapi_status.get("ok", False), "error": vlapi_status.get("error", ""),
                   "code": read_code(example_dir, "vlapi.js")},
            d3={"ok": d3_status.get("ok", False), "error": d3_status.get("error", ""),
                "code": read_code(example_dir, "d3.js")},
            ggplot={"ok": ggplot_status.get("ok", False), "error": ggplot_status.get("error", ""),
                    "code": read_code(example_dir, "ggplot.R"), "has_png": has_png},
            prev_name=names[i - 1] if i > 0 else None,
            next_name=names[i + 1] if i < len(names) - 1 else None,
        )
        examples.append(ctx)

    example_tpl = env.get_template("example.html.j2")
    for ctx in examples:
        out = example_tpl.render(**ctx)
        (EXAMPLES_DIR / ctx["name"]).mkdir(parents=True, exist_ok=True)
        (EXAMPLES_DIR / ctx["name"] / "index.html").write_text(out)

    by_name = {ex["name"]: ex for ex in examples}

    def card(ex):
        return dict(
            name=ex["name"], title=ex["title"], description=ex["description"],
            has_thumb=ex["has_thumb"],
            altair_ok=ex["altair"]["ok"], vlapi_ok=ex["vlapi"]["ok"], d3_ok=ex["d3"]["ok"],
            ggplot_ok=ex["ggplot"]["ok"] and ex["ggplot"]["has_png"],
        )

    # Mirror the official gallery's section > subsection > item structure for
    # every name it lists (100% of them exist in this corpus too, since both
    # come from the same vega-lite repo's examples/specs/ directory).
    sections = []
    for gs in gallery_sections:
        subsections = []
        for sub in gs["subsections"]:
            items = [card(by_name[n]) for n in sub["items"] if n in by_name]
            if items:
                subsections.append({"h3": sub["h3"], "cards": items})
        if subsections:
            sections.append({"h2": gs["h2"], "slug": slugify(gs["h2"]), "subsections": subsections})

    # Everything not in the official gallery: grouped by filename-prefix
    # category (e.g. "bar_foo" -> "bar"), alphabetically.
    leftover = [ex for ex in examples if not ex["in_gallery"]]
    by_category = {}
    for ex in leftover:
        by_category.setdefault(ex["category"], []).append(ex)
    extra_subsections = [
        {"h3": cat, "cards": [card(ex) for ex in sorted(by_category[cat], key=lambda e: e["name"])]}
        for cat in sorted(by_category)
    ]
    if extra_subsections:
        sections.append({
            "h2": "Additional Examples (test corpus, not in the curated gallery)",
            "slug": "additional-examples",
            "subsections": extra_subsections,
        })

    index_tpl = env.get_template("index.html.j2")
    (SHOWCASE / "index.html").write_text(index_tpl.render(
        sections=sections,
        total_count=len(examples),
        gallery_count=len(gallery_names),
    ))

    print(f"Built {len(examples)} example pages + index.html")
    for sysname, key in [("altair", "altair"), ("vlapi", "vlapi"), ("d3", "d3"), ("ggplot2", "ggplot")]:
        ok = sum(1 for ex in examples if (ex[key]["ok"] and (key != "ggplot" or ex[key]["has_png"])))
        print(f"  {sysname}: {ok}/{len(examples)} ok")


if __name__ == "__main__":
    main()
