// Generated by vl2plot.vegaLiteToPlotCode(spec, {ignoreUnsupported: true, includeSourcePaths: false})
import * as Plot from "@observablehq/plot";
import * as d3 from "d3";

export default async function chart(container, options = {}) {
  const wrapper = container.ownerDocument.createElement('div');
  wrapper.style.display = 'flex';
  wrapper.style.flexDirection = 'column';
  wrapper.style.gap = '1em';
  let chart1Data = await d3.csv(new URL("data/seattle-weather.csv", options.baseURL ?? import.meta.url), d3.autoType);
  chart1Data = chart1Data.map(d => ({...d, "date": new Date(d["date"])}));
  chart1Data = chart1Data.filter(d => true /* vl2d3: unsupported filter predicate shape {"param":"click"}, keeping every row (--ignore-unsupported) */);
  chart1Data = chart1Data.map(d => ({...d, "monthdate_date": new Date(2012, d.date.getMonth(), d.date.getDate())}));
  const chartNode1 = Plot.plot({
    document: container.ownerDocument,
    width: 600,
    height: 300,
    y: {domain: [-5, 40]},
    r: {domain: [-1, 50], range: [0, 20], legend: true},
    marks: [
      Plot.dot(chart1Data, {
    x: "monthdate_date",
    y: "temp_max",
    stroke: () => "lightgray",
    r: "precipitation",
  }),
    ],
  });
  wrapper.appendChild(chartNode1);
  let chart2Data = await d3.csv(new URL("data/seattle-weather.csv", options.baseURL ?? import.meta.url), d3.autoType);
  chart2Data = chart2Data.filter(d => true /* vl2d3: unsupported filter predicate shape {"param":"brush"}, keeping every row (--ignore-unsupported) */);
  const chartNode2 = Plot.plot({
    document: container.ownerDocument,
    width: 600,
    height: 200,
    marks: [
      Plot.barX(chart2Data, Plot.groupY({x: "count"}, {
    y: "weather",
    fill: () => "lightgray",
  })),
    ],
  });
  wrapper.appendChild(chartNode2);
  container.appendChild(wrapper);
  return wrapper;
}